refactor: restructure the whole thing
kyranet/veza pull request #211
Opened 2020-08-27 13:03 UTC by cfanoulis

### Description of the PR

give veza a bit of btf (read: favna) treatment

### Semver Classification

- [x] This PR only includes documentation or non-code changes.
- [x] This PR fixes a bug and does not change the (intended) API/interface.
- [ ] This PR adds methods or properties to the API/interface.
- [ ] This PR removes or renames methods or properties in the API/interface.

2020-08-27 13:16 UTC, Favna requested changes
please don't blindly copypaste...

2020-08-27 13:16 UTC, Favna commented on .eslintrc.json
> +{
Check what actually has to be included here. The globals don't have to be probably, `ban-types` and `unified-signatures` possibly neither. same for `no-namespace`. Also possibly `no-empty-function` and with that the entire override.

2020-08-27 13:16 UTC, Favna commented on LICENSE.md
> +Copyright © `2019` `Antonio Romàn`
```suggestion
Copyright © `2018` `Antonio Romàn`
```

2020-08-27 13:16 UTC, Favna commented on package.json
> +		],
remove this

2020-08-27 13:16 UTC, Favna commented on package.json
> +		"readme": "README.md",
```suggestion
```

2020-08-27 13:16 UTC, Favna commented on package.json
> +				"docs": "typedoc --excludeNotExported --exclude ./src/utils/**/*.ts --mode file --out ./dist/ ./src/",
wat?

2020-08-27 13:16 UTC, Favna commented on package.json
> +				"coverage:report": "yarn nyc report --reporter=cobertura",
```suggestion
```

2020-08-27 13:16 UTC, Favna commented on package.json
> +				"watch": "yarn build -w"
```suggestion
				"watch": "tsc -b src -w",
				"clean": "tsc -b src --clean"
```

2020-08-27 13:16 UTC, Favna commented on package.json
> +		],
```suggestion
```

2020-08-27 13:16 UTC, Favna commented on package.json
> +				"@skyra/eslint-config": "^5.3.0",
```suggestion
				"@skyra/eslint-config": "^5.3.1",
```

Just published this

2020-08-27 13:16 UTC, Favna commented on src/lib/Client.ts
> +/* eslint-disable @typescript-eslint/unified-signatures */
Already disabled globally

2020-08-27 13:16 UTC, Favna commented on src/lib/Structures/Base/SocketHandler.ts
>  				/* istanbul ignore next: Hard to reproduce, this is a safe-guard. */
remove all the istanbul ignore lines as we're using v8 coverage

2020-08-27 13:16 UTC, Favna commented on test/handshake.test.ts
> +beforeEach;
daheck is this line

2020-08-27 13:16 UTC, Favna commented on test/handshake.test.ts
> +		done.fail('This call should definitely crash.');
done.fail is not a function in Jest, that's an incorrect transformation. Remove it.

2020-08-27 13:16 UTC, Favna commented on tsconfig.base.json
> +		"lib": ["ESNext", "DOM"],
```suggestion
		"lib": ["ESNext"],
```

This lib doesn't need DOM

2020-08-27 13:16 UTC, Favna commented on tsconfig.base.json
> +		"target": "ESNext",
```suggestion
		"target": "ES2019",
```

2020-08-27 13:16 UTC, Favna commented on tsconfig.base.json
> +		"module": "ESNext",
```suggestion
```

This needs to be compiled to CommonJS not ESM

2020-08-27 13:16 UTC, Favna commented on tsconfig.eslint.json
> +	"include": ["src", "test", "examples", "jest.config.js", "rollup.config.ts"]
```suggestion
	"include": ["src", "test", "examples", "jest.config.js"]
```

There is no rollup config

2020-08-29 10:10 UTC, Favna requested changes

2020-08-29 10:10 UTC, Favna commented on test/handshake.test.ts
> +/* eslint-global fail*/
wat?

2020-08-29 10:10 UTC, Favna commented on test/handshake.test.ts
> +		done.fail('The socket should not try to connect.');
done.fail is not a function. I said that in previous review as well. Remove it. It's just `done()` though in most cases you shouldn't even need it.

2020-08-31 19:50 UTC, cfanoulis commented
it do be gone

2020-08-31 19:50 UTC, closed without merging